// Mocks generated by Mockito 5.0.16 from annotations
// in tdd_example/test/features/get_users/data/repositories/mocks.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tdd_example/core/network/network_info.dart' as _i6;
import 'package:tdd_example/features/get_users/data/data_sources/user_local_data_source.dart'
    as _i5;
import 'package:tdd_example/features/get_users/data/data_sources/user_remote_data_source.dart'
    as _i3;
import 'package:tdd_example/features/get_users/data/models/user_model.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeUserModel_0 extends _i1.Fake implements _i2.UserModel {}

/// A class which mocks [UserRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRemoteDataSource extends _i1.Mock
    implements _i3.UserRemoteDataSource {
  MockUserRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.UserModel>> getUsers() =>
      (super.noSuchMethod(Invocation.method(#getUsers, []),
              returnValue: Future<List<_i2.UserModel>>.value(<_i2.UserModel>[]))
          as _i4.Future<List<_i2.UserModel>>);
  @override
  _i4.Future<_i2.UserModel> getUser(int? id) =>
      (super.noSuchMethod(Invocation.method(#getUser, [id]),
              returnValue: Future<_i2.UserModel>.value(_FakeUserModel_0()))
          as _i4.Future<_i2.UserModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [UserLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserLocalDataSource extends _i1.Mock
    implements _i5.UserLocalDataSource {
  MockUserLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.UserModel>> getLastUsersModel() =>
      (super.noSuchMethod(Invocation.method(#getLastUsersModel, []),
              returnValue: Future<List<_i2.UserModel>>.value(<_i2.UserModel>[]))
          as _i4.Future<List<_i2.UserModel>>);
  @override
  _i4.Future<void> cacheUsers(List<_i2.UserModel>? usersToCache) =>
      (super.noSuchMethod(Invocation.method(#cacheUsers, [usersToCache]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  String toString() => super.toString();
}
